"""feeds table updated

Revision ID: 1d8ca3fde99d
Revises: a97863fd6547
Create Date: 2026-01-15 08:20:05.526969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8ca3fde99d'
down_revision = 'a97863fd6547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('guid', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('guid')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
