"""url unique

Revision ID: 2a82aafc8a65
Revises: 2b89f00a096d
Create Date: 2026-01-15 21:34:59.325570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a82aafc8a65'
down_revision = '2b89f00a096d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_feel_url', ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_constraint('uq_feel_url', type_='unique')

    # ### end Alembic commands ###
