"""feeds table

Revision ID: a97863fd6547
Revises: 73386def7ef4
Create Date: 2026-01-15 08:18:39.016369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97863fd6547'
down_revision = '73386def7ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_user_id'))
        batch_op.drop_index(batch_op.f('ix_feed_timestamp'))

    op.drop_table('feed')
    # ### end Alembic commands ###
