"""altered Feed table

Revision ID: c2f7b5b99327
Revises: 1d8ca3fde99d
Create Date: 2026-01-15 08:26:46.782109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f7b5b99327'
down_revision = '1d8ca3fde99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('guid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guid', sa.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
