"""articles

Revision ID: c8bb729c266e
Revises: 2a82aafc8a65
Create Date: 2026-01-16 19:32:17.859973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bb729c266e'
down_revision = '2a82aafc8a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_feel_url'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_feel_url'), ['url'])

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_timestamp'))
        batch_op.drop_index(batch_op.f('ix_article_feed_id'))

    op.drop_table('article')
    # ### end Alembic commands ###
