"""article unique url

Revision ID: ecf263e58820
Revises: 52a33a67ba42
Create Date: 2026-01-18 21:01:39.058005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf263e58820'
down_revision = '52a33a67ba42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_unique_constraint("hello", ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint("hello", type_='unique')

    # ### end Alembic commands ###
